name: Executar Rodo de Esportes

on:
  schedule:
    - cron: '0 */6 * * *' # Isso faz o robô rodar a cada 6 horas
  workflow_dispatch:      # Isso cria um botão para você rodar manualmente quando quiser

jobs:
  trabalho-de-coleta:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Ferramentas (npm)
        run: npm install

      - name: Rodar o Script de Coleta
        run: node rodo.js
        env:
          FIREBASE_CONFIG: ${{ secrets.CONFIG_FIREBASE }}
          API_KEY_ESPORTES: ${{ secrets.CHAVE_API_ESPORTES }}
