name: Executar Rodo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  job_coleta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Rodar Script
        run: |
          npm install
          node rodo.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          API_KEY_ESPORTES: ${{ secrets.CHAVE_API_ESPORTES }}
