name: Executar Rodo Ante Span

on:
  workflow_dispatch:  # rodar manualmente
  schedule:
    - cron: '0 */6 * * *'  # rodar a cada 6 horas

jobs:
  job_coleta:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixa o código
      - uses: actions/checkout@v3

      # 2️⃣ Configura Node 18
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Instala dependências
      - name: Instalar dependências
        run: npm install

      # 4️⃣ Executa o robô
      - name: Rodar Rodo.js
        run: node rodo.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          API_1_URL: ${{ secrets.API_1_URL }}
          API_2_URL: ${{ secrets.API_2_URL }}
          API_3_URL: ${{ secrets.API_3_URL }}
          API_4_URL: ${{ secrets.API_4_URL }}
          API_5_URL: ${{ secrets.API_5_URL }}
