name: Executar Rodo Ante Span Multi-API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  job_coleta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar Rodo.js
        run: node rodo.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          API_1_URL: ${{ secrets.API_1_URL }}
          API_2_URL: ${{ secrets.API_2_URL }}
          API_3_URL: ${{ secrets.API_3_URL }}
          API_4_URL: ${{ secrets.API_4_URL }}
          API_4_KEY: ${{ secrets.API_4_KEY }}
